### ISSUE TITLE
Same thing about tests again, thanks!

### ISSUE THREAD

**Issue by rfay** [hanoii/ddev-platformsh-lite#1]

**Comment by hanoii** [comment]
I'll remove the label here. I am still maintaining it and depending on it for all of my platform projects but probably not for everyone. I'll review if I change my mind

**Comment by rfay** [comment]
I'd love to talk with you about the future of ddev-platformsh. It needs some real love and etc. Could we do a zoom sometime soon? You working today?

**Comment by hanoii** [comment]
@rfay sure, although I might be working today, I think is best over the week, ping me on Mon (or I will) and we can schedule something.

**Comment by rfay** [comment]
Thanks, would love to hear your perspective on what you've tried to do with this and your experience with ddev-platformsh.
